### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by elezar**
Add reference to STUPS documentation.

@mikkeloscar please review.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@elezar I expect there will be some senza file as well?

**Comment by elezar** [comment]
I was thinking of adding one, but was unsure on how to adjust this for the public documentation. Are there some Senza variables to generate the default mint bucket, for example? The pierone registry will also need to be modified.

**Comment by mikkeloscar** [comment]
Just make it senza arguments which can be passed with `senza create` I think it's pretty clear you have to substitute with the real value

**Comment by elezar** [comment]
OK. I will do so. Can we merge this PR first?

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
